name: Docker
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set sha
      id: sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set branch name
      id: branch
      run: |
        if [ ${{ github.event_name }} == "pull_request" ];then
          echo "::set-output name=branch_name::${{ github.head_ref }}"
        elif [ ${{ github.event_name }} == "push" ]
        then
          echo "::set-output name=branch_name::${{ github.ref }}"
        fi

    - name: Build and push Docker images for Solomon
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: satapps/terriamap
        dockerfile: ./deploy/docker-alternate/alternate.Dockerfile
        tags: ${{ steps.branch.outputs.branch_name }}-sha-${{ steps.sha.outputs.sha_short }}-solomon
        target: solomon_build

    - name: Build and push Docker images for Vanuatu
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: satapps/terriamap
        dockerfile: ./deploy/docker-alternate/alternate.Dockerfile
        tags: ${{ steps.branch.outputs.branch_name }}-sha-${{ steps.sha.outputs.sha_short }}-vanuatu
        target: vanuatu_build
